### PR TITLE
Support other browsers

### PR DESCRIPTION
**Pull request by Termit1975**
Please add support for other major browser with this commit.

### CODE REVIEW

**Comment by Termit1975** [comment]
Not very familiar with git... 
Please only pick  65823df00832ea4b6a97c1dedfe23975d0cb783c
The other one is the one that caches the SourceMapConsumer

**Comment by novocaine** [comment]
thank you for this, will review soon

**Comment by Termit1975** [comment]
Any news on this PR?

**Comment by novocaine** [comment]
Sorry! Will try to get to it this weekend

**Comment by sylvain-hamel** [comment]
Hello @novocaine can you please publish this fix. Thanks

**Comment by novocaine** [comment]
This has been merged and published as 1.1.7

**Pull request merged**
